name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "false"
        
    - name: Build binary
      uses: houseabsolute/actions-rust-cross@v0
      with:
        command: build
        target: arm-unknown-linux-gnueabihf
        args: "--locked --release"
        strip: true
        
    - name: Package as archive
      shell: bash
      run: | 
        ls -la target/arm-unknown-linux-gnueabihf/release
        cp target/arm-unknown-linux-gnueabihf/release/discord_status_bot discord_status_bot

    - name: Copy over
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "discord_status_bot"
        target: ${{ secrets.TARGET_DIR }}
