name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "false"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .github/image
        tags: arm-unknown-linux-gnueabihf:protoc
        
    - name: Build binary
      uses: houseabsolute/actions-rust-cross@v0
      with:
        command: build
        target: arm-unknown-linux-gnueabihf
        args: "--locked --release"
        strip: true
        
    - name: Package as archive
      shell: bash
      run: |
        cp target/arm-unknown-linux-gnueabihf/release/discord_status_bot discord_status_bot

    - name: Copy over
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "discord_status_bot"
        target: ${{ secrets.TARGET_DIR }}

    - name: Restarting the job
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: cd ${{secrets.TARGET_DIR}} && ./start_job.sh
